<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_db
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author    zetta
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase abstracta para los CRUDS
 * @category   lib
 * @package    lib_db
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta 
 * @version    1.0.0 SVN: $Revision$
 */
abstract class CrudController extends BaseController
{
    
    /**
     * list all objects
     */
    abstract public function listAction();
    
    /**
     * delete an object
     */
    abstract public function deleteAction();
    
    /**
     * Form to edit an object
     */
    abstract public function editAction();
    
    /**
     * Create an Object
     */
    abstract public function createAction();
    
    /**
     * Update an Object
     */
    abstract public function updateAction();
    
}


