<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   Application
 * @package    Application_Controllers
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * AlbumController (CRUD for the Album Objects)
 *
 * @category   Project
 * @package    Project_Controllers
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class AlbumController extends CrudController
{
    
    /**
     * alias for the list action
     */
    public function indexAction()
    {
        $this->_forward('list');
    }
    
    /**
     * List the objects Album actives
     */
    public function listAction()
    {
        $this->view->albums = AlbumCatalog::getInstance()->getActives();
        $this->setTitle('List the Album');
    }
    
    /**
     * delete an Album
     */
    public function deleteAction()
    {
        $albumCatalog = AlbumCatalog::getInstance();
        $idAlbum = $this->getRequest()->getParam('idAlbum');
        $album = $albumCatalog->getById($idAlbum);
        $albumCatalog->deactivate($album);
        $this->setFlash('ok','Successfully removed the Album');
        $this->_redirect('album/list');
    }
    
    /**
     * Form for edit an Album
     */
    public function editAction()
    {
        $albumCatalog = AlbumCatalog::getInstance();
        $idAlbum = $this->getRequest()->getParam('idAlbum');
        $album = $albumCatalog->getById($idAlbum);
        $post = array(
            'id_album' => $album->getIdAlbum(),
            'id_user' => $album->getIdUser(),
            'title' => $album->getTitle(),
        );
        $this->view->post = $post;
        $this->setTitle('Edit Album');
    }
    
    /**
     * Create an Album
     */
    public function createAction()
    {   
        $albumCatalog = AlbumCatalog::getInstance();
        $idUser = utf8_decode($this->getRequest()->getParam('id_user'));
        $title = utf8_decode($this->getRequest()->getParam('title'));
        $album = AlbumFactory::create($idUser, $title);
        $albumCatalog->create($album);  
        $this->view->setTpl('_row');
        $this->view->setLayoutFile(false);
        $this->view->album = $album;
    }
    
    /**
     * Update an Album
     */
    public function updateAction()
    {
        $albumCatalog = AlbumCatalog::getInstance();
        $idAlbum = $this->getRequest()->getParam('idAlbum');
        $album = $albumCatalog->getById($idAlbum);
        $album->setIdUser($this->getRequest()->getParam('id_user'));
        $album->setTitle($this->getRequest()->getParam('title'));
        $albumCatalog->update($album);
        $this->setFlash('ok','Successfully edited the Album');
        $this->_redirect('album/list');
    }
    
}
