<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   Application
 * @package    Application_Controllers
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * UserController (CRUD for the User Objects)
 *
 * @category   Project
 * @package    Project_Controllers
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class UserController extends CrudController
{
    
    /**
     * alias for the list action
     */
    public function indexAction()
    {
        $this->_forward('list');
    }
    
    /**
     * List the objects User actives
     */
    public function listAction()
    {
        $this->view->users = UserCatalog::getInstance()->getActives();
        $this->setTitle('List the User');
    }
    
    /**
     * delete an User
     */
    public function deleteAction()
    {
        $userCatalog = UserCatalog::getInstance();
        $idUser = $this->getRequest()->getParam('idUser');
        $user = $userCatalog->getById($idUser);
        $userCatalog->deactivate($user);
        $this->setFlash('ok','Successfully removed the User');
        $this->_redirect('user/list');
    }
    
    /**
     * Form for edit an User
     */
    public function editAction()
    {
        $userCatalog = UserCatalog::getInstance();
        $idUser = $this->getRequest()->getParam('idUser');
        $user = $userCatalog->getById($idUser);
        $post = array(
            'id_user' => $user->getIdUser(),
            'id_person' => $user->getIdPerson(),
            'username' => $user->getUsername(),
            'password' => $user->getPassword(),
        );
        $this->view->post = $post;
        $this->setTitle('Edit User');
    }
    
    /**
     * Create an User
     */
    public function createAction()
    {   
        $userCatalog = UserCatalog::getInstance();
        $idPerson = utf8_decode($this->getRequest()->getParam('id_person'));
        $username = utf8_decode($this->getRequest()->getParam('username'));
        $password = utf8_decode($this->getRequest()->getParam('password'));
        $user = $userCatalog->getByUsername($username);
        if( !($user instanceof User) )
        {
            $user = UserFactory::create($idPerson, $username, $password);
            $userCatalog->create($user);
        }
        $userCatalog->activate($user);
        $this->view->setTpl('_row');
        $this->view->setLayoutFile(false);
        $this->view->user = $user;
    }
    
    /**
     * Update an User
     */
    public function updateAction()
    {
        $userCatalog = UserCatalog::getInstance();
        $idUser = $this->getRequest()->getParam('idUser');
        $user = $userCatalog->getById($idUser);
        $user->setIdPerson($this->getRequest()->getParam('id_person'));
        $user->setUsername($this->getRequest()->getParam('username'));
        $user->setPassword($this->getRequest()->getParam('password'));
        $userCatalog->update($user);
        $this->setFlash('ok','Successfully edited the User');
        $this->_redirect('user/list');
    }
    
}
