<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_db
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author    zetta
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Interfaz Catalog
 * @category   lib
 * @package    lib_db
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta 
 * @version    1.0.0 SVN: $Revision$
 */
interface CatalogInterface 
{
    /**
     * Método público abstracto que permite tener solo una instancia del catálogo
     */
    public static function getInstance();


    /**
     * Guarda en la base de datos
     * @param mixed Un bean para guardar
     */
    public function create($object);
    
    /**
     * Actualiza el objeto en la base de datos
     * @param mixed Un bean para actualizar
     */
    public function update($object);
    
    /**
     * Elimina de  la base de datos
     * @param mixed El bean que se va a eliminar
     */
    public function delete($object);
    
    /**
     * Elimina de la base de datos por medio de llave primaria
     * @param int $idObject El id del bean que se borrará
     */
    public function deleteById($idObject);
    
    /**
     * Obtiene un BEAN de la base de datos
     * @param int $idObject 
     * @return mixed EL BEAN
     */
    public function getById($idObject);
    
    /**
     * Obtiene un arreglo de todos los ids =S
     * @return array
     */
    public function retrieveAllIds();
    
  
    /**
     * Obtiene un arreglo de ids determinados por un criteria
     * @param Criteria $criteria
     * @return array 
     */
    public function getIdsByCriteria(Criteria $criteria = null);
    
    /**
     * Obtiene un BEAN por el criteria especificado
     * @param Criteria $criteria
     * @return mixed EL BEAN
     */
    public function getByCriteria(Criteria $criteria = null);
    
    /**
     * Obtiene un arreglo de valores establecidos por el usuario
     * @param Criteria $criteria
     * @param string $field Nombre del campo
     * @return array
     */
    public function getCustomFieldByCriteria($field, Criteria $criteria = null);
    

}


