<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_db
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase que representa la abstraccion de nuestro objeto Zend_Db
 *
 * @category   lib
 * @package    lib_db
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta 
 * @version    1.0.0 SVN: $Revision$
 */
abstract class DBAO
{

    /**
     * @var Zend_Db_Adapter_Abstract
     */
    public static $config = null;

    /**
     * Instancia singleton
     */
    static protected $instance  = null;
    
    /**
     * Regresa el objeto Zend_Db para los catalogos
     * @return Zend_Db_Adapter_Abstract Objeto Zend_Db_Adapter_Abstract para manejo de la Base de datos
     * @throws Exception No se ha configurado el parametro estático de la base de datos
     */
    public static function Database()
    {
        if(DBAO::$config === null)
        {
            throw new Exception("No se ha configurado el parametro estático de la base de datos");
        }
        return DBAO::getInstance();
    }

    
    /**
     * Método para obtener la instancia del catálogo, solo el método DBAO::Database() puede acceder a el
     * @return Zend_Db_Adapter_Abstract
     */
    private static function getInstance()
    {
        if (!isset(self::$instance))
        {
          self::$instance = Zend_Db::factory(DBAO::$config);
        }
        return self::$instance;
    }
}

