<?php
/**
 * Bender
 * @author Juan Carlos Jarquin
 * @author Vicente Mendoza
 */

/**
 * BenderClass
 */
final class Bender
{
    /**
     * Bender Version
     */
    const VERSION = '1.0.2';

    /**
     * The Bender Signature
     * @var string
     */
    const SIGNATURE = "This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>";

}
