<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase AlbumCollection que representa una collección de objetos Album
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class AlbumCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('Album');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param Album $album
     */
    public function append($album)
    {
        parent::offsetSet($album->getIdAlbum(), $album);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return Album
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return Album 
     */
    public function read()
    {
        $album = $this->current();
        $this->next();
        return $album;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return Album|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idAlbum
     * @param  int $idAlbum
     * @return boolean
     */
    public function contains($idAlbum)
    {
        return parent::offsetExists($idAlbum);
    }
    
    /**
     * Merge two Collections
     * @param AlbumCollection $albumCollection
     * @return void
     */
    public function merge(AlbumCollection $albumCollection)
    {
        while($albumCollection->valid())
        {
            $album = $albumCollection->read();
            if( !$this->contains( $album->getIdAlbum() ) )
            {
                $this->append($album);
            }             
        }
        $albumCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the Album with primary key  
     * @param  int $idAlbum
     * @return Album
     */
    public function getByPK($idAlbum)
    {
        return $this->contains($idAlbum) ? $this[$idAlbum] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $album = $this->read();
            $this->parser->changeBean($album);
            $array[$album->getIdAlbum()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $album = $this->read();
            $this->parser->changeBean($album);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

