<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase PersonCollection que representa una collección de objetos Person
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class PersonCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('Person');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param Person $person
     */
    public function append($person)
    {
        parent::offsetSet($person->getIdPerson(), $person);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return Person
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return Person 
     */
    public function read()
    {
        $person = $this->current();
        $this->next();
        return $person;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return Person|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idPerson
     * @param  int $idPerson
     * @return boolean
     */
    public function contains($idPerson)
    {
        return parent::offsetExists($idPerson);
    }
    
    /**
     * Merge two Collections
     * @param PersonCollection $personCollection
     * @return void
     */
    public function merge(PersonCollection $personCollection)
    {
        while($personCollection->valid())
        {
            $person = $personCollection->read();
            if( !$this->contains( $person->getIdPerson() ) )
            {
                $this->append($person);
            }             
        }
        $personCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the Person with primary key  
     * @param  int $idPerson
     * @return Person
     */
    public function getByPK($idPerson)
    {
        return $this->contains($idPerson) ? $this[$idPerson] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $person = $this->read();
            $this->parser->changeBean($person);
            $array[$person->getIdPerson()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $person = $this->read();
            $this->parser->changeBean($person);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

