<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase PhotoCollection que representa una collección de objetos Photo
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class PhotoCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('Photo');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param Photo $photo
     */
    public function append($photo)
    {
        parent::offsetSet($photo->getIdPhoto(), $photo);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return Photo
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return Photo 
     */
    public function read()
    {
        $photo = $this->current();
        $this->next();
        return $photo;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return Photo|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idPhoto
     * @param  int $idPhoto
     * @return boolean
     */
    public function contains($idPhoto)
    {
        return parent::offsetExists($idPhoto);
    }
    
    /**
     * Merge two Collections
     * @param PhotoCollection $photoCollection
     * @return void
     */
    public function merge(PhotoCollection $photoCollection)
    {
        while($photoCollection->valid())
        {
            $photo = $photoCollection->read();
            if( !$this->contains( $photo->getIdPhoto() ) )
            {
                $this->append($photo);
            }             
        }
        $photoCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the Photo with primary key  
     * @param  int $idPhoto
     * @return Photo
     */
    public function getByPK($idPhoto)
    {
        return $this->contains($idPhoto) ? $this[$idPhoto] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $photo = $this->read();
            $this->parser->changeBean($photo);
            $array[$photo->getIdPhoto()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $photo = $this->read();
            $this->parser->changeBean($photo);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

