<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase UserCollection que representa una collección de objetos User
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class UserCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('User');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param User $user
     */
    public function append($user)
    {
        parent::offsetSet($user->getIdUser(), $user);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return User
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return User 
     */
    public function read()
    {
        $user = $this->current();
        $this->next();
        return $user;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return User|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idUser
     * @param  int $idUser
     * @return boolean
     */
    public function contains($idUser)
    {
        return parent::offsetExists($idUser);
    }
    
    /**
     * Merge two Collections
     * @param UserCollection $userCollection
     * @return void
     */
    public function merge(UserCollection $userCollection)
    {
        while($userCollection->valid())
        {
            $user = $userCollection->read();
            if( !$this->contains( $user->getIdUser() ) )
            {
                $this->append($user);
            }             
        }
        $userCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the User with primary key  
     * @param  int $idUser
     * @return User
     */
    public function getByPK($idUser)
    {
        return $this->contains($idUser) ? $this[$idUser] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $user = $this->read();
            $this->parser->changeBean($user);
            $array[$user->getIdUser()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $user = $this->read();
            $this->parser->changeBean($user);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

