bender:
  db:
    dsn:                     sqlite:application/config/bender.db
    username:                root
    password:                temporal
    schema_file:             default
  add_bender_signature:      true
  encoding:                  UTF-8
  header:
    author:                  PUT_YOUR_NAME_HERE
    brand_name:              PUT_YOUR_BRAND_NAME_HERE
    copyright:               PUT_YOUR_COPYRIGHT_INFORMATION_HERE
    description:             PUT_A_SIMPLE_DESCRIPTION_HERE
