<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase Album
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class Album
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "albums";
    const TABLENAME_ALBUM_PHOTO = 'albums_photos';

    /**
     * Constantes para los nombres de los campos
     */
    const ID_ALBUM = "albums.id_album";
    const ID_USER = "albums.id_user";
    const TITLE = "albums.title";
    

    /**
     * $idAlbum 
     * 
     * @var int $idAlbum
     */
    private $idAlbum;
    

    /**
     * $idUser 
     * 
     * @var int $idUser
     */
    private $idUser;
    

    /**
     * $title 
     * 
     * @var string $title
     */
    private $title;

    /**
     * Set the idAlbum value
     * 
     * @param int idAlbum
     * @return Album $album
     */
    public function setIdAlbum($idAlbum)
    {
        $this->idAlbum = $idAlbum;
        return $this;
    }

    /**
     * Return the idAlbum value
     * 
     * @return int
     */
    public function getIdAlbum()
    {
        return $this->idAlbum;
    }

    /**
     * Set the idUser value
     * 
     * @param int idUser
     * @return Album $album
     */
    public function setIdUser($idUser)
    {
        $this->idUser = $idUser;
        return $this;
    }

    /**
     * Return the idUser value
     * 
     * @return int
     */
    public function getIdUser()
    {
        return $this->idUser;
    }

    /**
     * Set the title value
     * 
     * @param string title
     * @return Album $album
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * Return the title value
     * 
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

}
