<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase Person
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class Person
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "persons";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_PERSON = "persons.id_person";
    const FIRST_NAME = "persons.first_name";
    const LAST_NAME = "persons.last_name";
    

    /**
     * $idPerson 
     * 
     * @var int $idPerson
     */
    private $idPerson;
    

    /**
     * $firstName 
     * 
     * @var string $firstName
     */
    private $firstName;
    

    /**
     * $lastName 
     * 
     * @var string $lastName
     */
    private $lastName;

    /**
     * Set the idPerson value
     * 
     * @param int idPerson
     * @return Person $person
     */
    public function setIdPerson($idPerson)
    {
        $this->idPerson = $idPerson;
        return $this;
    }

    /**
     * Return the idPerson value
     * 
     * @return int
     */
    public function getIdPerson()
    {
        return $this->idPerson;
    }

    /**
     * Set the firstName value
     * 
     * @param string firstName
     * @return Person $person
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * Return the firstName value
     * 
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set the lastName value
     * 
     * @param string lastName
     * @return Person $person
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * Return the lastName value
     * 
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

}
