<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase Photo
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class Photo
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "photos";
    const TABLENAME_PHOTO_ALBUM = 'albums_photos';

    /**
     * Constantes para los nombres de los campos
     */
    const ID_PHOTO = "photos.id_photo";
    const ID_USER = "photos.id_user";
    const TITLE = "photos.title";
    const URI = "photos.uri";
    

    /**
     * $idPhoto 
     * 
     * @var int $idPhoto
     */
    private $idPhoto;
    

    /**
     * $idUser 
     * 
     * @var int $idUser
     */
    private $idUser;
    

    /**
     * $title 
     * El titulo de la fotografia
     * @var string $title
     */
    private $title;
    

    /**
     * $uri 
     * 
     * @var string $uri
     */
    private $uri;

    /**
     * Set the idPhoto value
     * 
     * @param int idPhoto
     * @return Photo $photo
     */
    public function setIdPhoto($idPhoto)
    {
        $this->idPhoto = $idPhoto;
        return $this;
    }

    /**
     * Return the idPhoto value
     * 
     * @return int
     */
    public function getIdPhoto()
    {
        return $this->idPhoto;
    }

    /**
     * Set the idUser value
     * 
     * @param int idUser
     * @return Photo $photo
     */
    public function setIdUser($idUser)
    {
        $this->idUser = $idUser;
        return $this;
    }

    /**
     * Return the idUser value
     * 
     * @return int
     */
    public function getIdUser()
    {
        return $this->idUser;
    }

    /**
     * Set the title value
     * El titulo de la fotografia
     * @param string title
     * @return Photo $photo
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * Return the title value
     * El titulo de la fotografia
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set the uri value
     * 
     * @param string uri
     * @return Photo $photo
     */
    public function setUri($uri)
    {
        $this->uri = $uri;
        return $this;
    }

    /**
     * Return the uri value
     * 
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }

}
