<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase Test
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class Test
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "non_primary_table";

    /**
     * Constantes para los nombres de los campos
     */
    const NAME = "non_primary_table.name";
    const NUMBER = "non_primary_table.number";
    const DATA = "non_primary_table.data";
    

    /**
     * $name 
     * 
     * @var string $name
     */
    private $name;
    

    /**
     * $number 
     * 
     * @var int $number
     */
    private $number;
    

    /**
     * $data 
     * 
     * @var string $data
     */
    private $data;

    /**
     * Set the name value
     * 
     * @param string name
     * @return Test $test
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Return the name value
     * 
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the number value
     * 
     * @param int number
     * @return Test $test
     */
    public function setNumber($number)
    {
        $this->number = $number;
        return $this;
    }

    /**
     * Return the number value
     * 
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Set the data value
     * 
     * @param string data
     * @return Test $test
     */
    public function setData($data)
    {
        $this->data = $data;
        return $this;
    }

    /**
     * Return the data value
     * 
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

}
