<?php
/**
 * Bender
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase User
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class User extends Person 
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "users";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_USER = "users.id_user";
    const ID_PERSON = "users.id_person";
    const USERNAME = "users.username";
    const PASSWORD = "users.password";
    

    /**
     * $idUser 
     * 
     * @var int $idUser
     */
    private $idUser;
    

    /**
     * $idPerson 
     * 
     * @var int $idPerson
     */
    private $idPerson;
    

    /**
     * $username 
     * 
     * @var string $username
     */
    private $username;
    

    /**
     * $password 
     * 
     * @var string $password
     */
    private $password;

    /**
     * Set the idUser value
     * 
     * @param int idUser
     * @return User $user
     */
    public function setIdUser($idUser)
    {
        $this->idUser = $idUser;
        return $this;
    }

    /**
     * Return the idUser value
     * 
     * @return int
     */
    public function getIdUser()
    {
        return $this->idUser;
    }

    /**
     * Set the idPerson value
     * 
     * @param int idPerson
     * @return User $user
     */
    public function setIdPerson($idPerson)
    {
        $this->idPerson = $idPerson;
        return $this;
    }

    /**
     * Return the idPerson value
     * 
     * @return int
     */
    public function getIdPerson()
    {
        return $this->idPerson;
    }

    /**
     * Set the username value
     * 
     * @param string username
     * @return User $user
     */
    public function setUsername($username)
    {
        $this->username = $username;
        return $this;
    }

    /**
     * Return the username value
     * 
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set the password value
     * 
     * @param string password
     * @return User $user
     */
    public function setPassword($password)
    {
        $this->password = $password;
        return $this;
    }

    /**
     * Return the password value
     * 
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

}
